version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: 
      - "github_actions"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "crazy-max/ghaction-import-gpg"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "rimraf"
