services:
  preview:
    command: node ./build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  dev:
    command: npm run dev
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    ports:
      - 8443:8443
      - 443:443
    volumes:
      - .:/usr/src/app
