name: 'CI Pipeline'
on:
  pull_request:
    branches-ignore:
      - dependabot/**
jobs:
  pr:
    strategy:
      matrix:
        node: [16.x] # tests both npm 7 & 8
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node }} Run
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run ci
      - run: npx playwright install  --with-deps
      - name: E2E
        run: npm run ci:e2e
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # https://www.chromatic.com/docs/github-actions#ui-test-and-ui-review
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
