name: 'CI Pipeline'
on:
  pull_request:
    branches-ignore:
      - dependabot/**
jobs:
  pr:
    strategy:
      matrix:
        node: [16.x]
        os: [macos-latest, ubuntu-latest] #, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node }} Run
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: npx playwright install  --with-deps
      - name: E2E
        run: npm run ci:e2e
      - name: Publish to Chromatic
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
