# file: .github/workflows/preview-closed.yaml
on:
  pull_request:
    types:
      - closed
jobs:
  closed:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ryanbas21/update-cors-am-github-action:main
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          url: ${{secrets.OKTETO_URL}}
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Get Preview Endpoints
        id: preview_urls
        run: |
          URLS=$(okteto preview endpoints pr-${{ github.event.number }}-ryanbas21 -o json | jq -c)
          echo "preview_urls=$URLS" >> "$GITHUB_OUTPUT"
      - uses: ryanbas21/update-cors-am-github-action@latest
        with:
          AM_URL: ${{ secrets.VITE_FR_AM_URL }}
          USERNAME: ${{ secrets.AM_USERNAME }}
          PASSWORD: ${{ secrets.AM_PASSWORD }}
          REALM_PATH: ${{ secrets.VITE_FR_REALM_PATH }}
          ORIGINS: ${{ steps.preview_urls.outputs.preview_urls }}
          COOKIE_NAME: ${{ secrets.VITE_FR_AM_COOKIE_NAME }}
          REDIRECTION_URIS: ${{ secrets.REDIRECTION_URIS }}
          REMOVE: true
          CORS_CONFIG_NAME: 'org-ui'
      - name: Destroy preview environment
        uses: okteto/destroy-preview@latest
        with:
          name: pr-${{ github.event.number }}-ryanbas21
